name: webpack-cli

on:
  push:
    branches:
      - main
      - next
  pull_request:
    branches:
      - main
      - next

permissions:
  contents: read

jobs:
  lint:
    name: Lint - ${{ matrix.os }} - Node v${{ matrix.node-version }}
    runs-on: ${{ matrix.os }}
    concurrency:
      group: lint-${{ github.ref }}
      cancel-in-progress: true
    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [18.x]
        webpack-version: [latest]
    steps:
      - uses: actions/checkout@v4

      - name: Using Node v${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "yarn"

      - name: Install dependencies
        run: yarn --frozen-lockfile --ignore-engines

      - name: Build
        run: yarn build

      - name: Lint
        run: yarn lint

  build:
    name: Tests and Coverage - ${{ matrix.os }} - Node v${{ matrix.node-version }}, Webpack ${{ matrix.webpack-version }}, DevServer ${{ matrix.dev-server-version }} (${{ matrix.shard }})
    runs-on: ${{ matrix.os }}
    concurrency:
      group: build-${{ github.ref }}
      cancel-in-progress: true
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node-version: [18.x, 20.x, 22.x, 24.x]
        shard: ["1/4", "2/4", "3/4", "4/4"]
        webpack-version: [latest]
        dev-server-version: [latest]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Using Node v${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "yarn"

      - uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Install dependencies
        run: yarn --frozen-lockfile --ignore-engines --ignore-scripts

      - name: Prepare environment for tests
        run: yarn build:ci

      - name: Run tests and generate coverage
        run: yarn test:coverage --ci --shard=${{ matrix.shard }}

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          verbose: true

  smoketests:
    name: Smoketests - ${{ matrix.os }} - Node v${{ matrix.node-version }}
    runs-on: ${{ matrix.os }}
    concurrency:
      group: smoketests-${{ github.ref }}
      cancel-in-progress: true
    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [lts/*]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Using Node v${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "yarn"

      - name: Install dependencies
        run: yarn --frozen-lockfile --ignore-engines
  smoketests:
    name: Smoketests - ${{ matrix.os }} - Node v${{ matrix.node-version }}
    runs-on: ubuntu-latest
    concurrency:
      group: smoketests-${{ github.ref }}
      cancel-in-progress: true
    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [lts/*]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Using Node v${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "yarn"

      - name: Install dependencies
        run: yarn --frozen-lockfile --ignore-engines

